server {
    listen 8081;
    server_name _; # Accepte les requêtes de n'importe quel nom de domaine/IP rejoignant ce port

    location /media/ {
        # Le dossier à l'intérieur du conteneur Nginx où se trouvent les images
        alias /var/serv-media/;

        # Sécurité : désactivé en prod pour éviter que n'importe qui puisse lister vos dossiers
        autoindex off;

        # CORS : Indispensable pour que votre application Angular (port 8080 ou autre) puisse afficher les images
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods 'GET, OPTIONS';
        add_header Access-Control-Allow-Headers 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
    }

    # (Optionnel) Si cet Nginx sert également votre application Angular compilée :
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
