name: Deploy Venus Project

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Force cleanup and Deploy
        env:
          DOCKER_API_VERSION: "1.43"
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
        run: |
          docker rm -f ***-db || true
          docker-compose up -d --build --remove-orphans
                  
      - name: Cleanup old images
        run: docker image prune -f
