name: Deploy Venus Project

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build new images
        run: docker-compose build --pull

      - name: Stop and remove old containers
        run: docker-compose down

      - name: Deploy new stack
        env:
          DOCKER_API_VERSION: "1.43"
          COMPOSE_PROJECT_NAME: venus
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
        run: |
          docker-compose -p venus down
          docker-compose -p venus up -d --remove-orphans
                  
      - name: Cleanup old images
        env:
          DOCKER_API_VERSION: "1.43"
        run: |
          docker image prune -f